version: '3.8'

services:
  postgres:
    image: postgres:17.5-bookworm
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salonSync
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: salonSyncAPI
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: salonSync

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/ssl:ro
    depends_on:
      - salonSyncAPI
    restart: always
  

volumes:
  postgres_data: